---
authHeader: "X-Wepba-Client"
authDelimiter: "="
webhookRequest:
  config:
    url: "http://localhost:7100/endpoint"
    secret: "SECRET"
  events: [".*"]
webhookRegistrationURL: "localhost:8000/hook"
webhookTimeout: "10s"
webhookRegistrationInterval: "4m"
port: ":7100"
endpoint: "/endpoint"
responseCode: 202